"""
schemas/emvco_3ds_schema.py
EMVCo 3-D Secure (3DS) v2.x column specification.

All data elements follow the EMVCo 3DS Core Specification v2.3.1
(https://www.emvco.com/emv-technologies/3-d-secure/).

Columns are grouped by the EMVCo message category they belong to:
  - Transaction Identification
  - Cardholder / Account Information
  - Device / Browser Fingerprint (deviceChannel = "02" BRW, "01" APP)
  - Merchant & Acquirer Information
  - Authentication Request / Response
  - Risk / 3RI Signals
  - Fraud Label (synthetic ground-truth, not part of EMVCo spec)

The DatasetEngine reads EMVCO_3DS_COLUMNS to know which columns to produce
and their dtypes.  The blueprint prompt reads EMVCO_COLUMN_DESCRIPTIONS for
the in-prompt reference table.
"""

from __future__ import annotations

# ── EMVCo 3DS Column Definitions ──────────────────────────────────────────────
# Each entry: (column_name, dtype, emvco_element_id, description)
# dtype: "str" | "int" | "float" | "bool" | "datetime" | "enum"

EMVCO_3DS_COLUMNS: list[tuple[str, str, str, str]] = [

    # ── Transaction Identification ─────────────────────────────────────────────
    ("threeds_server_trans_id",   "str",      "3DSServerTransID",      "UUID assigned by 3DS Server for this authentication"),
    ("acs_trans_id",              "str",      "acsTransID",            "UUID assigned by ACS for this authentication"),
    ("ds_trans_id",               "str",      "dsTransID",             "UUID assigned by Directory Server"),
    ("sdk_trans_id",              "str",      "sdkTransID",            "UUID generated by 3DS SDK (app-based channel only)"),
    ("message_version",           "enum",     "messageVersion",        "3DS protocol version: 2.1.0 | 2.2.0 | 2.3.1"),
    ("device_channel",            "enum",     "deviceChannel",         "01=APP (SDK), 02=BRW (browser), 03=3RI (requestor-initiated)"),
    ("three_ds_requestor_id",     "str",      "threeDSRequestorID",    "Merchant's 3DS Requestor ID registered with DS"),
    ("three_ds_requestor_name",   "str",      "threeDSRequestorName",  "Merchant's 3DS Requestor name"),

    # ── Cardholder & Account Information ──────────────────────────────────────
    ("acct_number",               "str",      "acctNumber",            "PAN (masked: first 6 + last 4 visible)"),
    ("card_expiry_date",          "str",      "cardExpiryDate",        "YYMM expiry date from PAN"),
    ("acct_id",                   "str",      "acctID",                "Cardholder account identifier at merchant"),
    ("acct_type",                 "enum",     "acctType",              "01=Not Applicable, 02=Credit, 03=Debit"),
    ("acct_info_chg_ind",         "enum",     "acctInfo.chgInd",       "01=Changed this txn, 02=<30d, 03=30-60d, 04=>60d"),
    ("acct_info_open_acct_ind",   "enum",     "acctInfo.openAcctInd",  "01=New acct, 02=<30d, 03=30-60d, 04=>60d"),
    ("acct_info_ship_addr_usage_ind","enum",  "acctInfo.shipAddrUsageInd","01=This txn, 02=<30d, 03=30-60d, 04=>60d"),
    ("acct_info_txn_activity_day","int",      "acctInfo.txnActivityDay","Txns on cardholder account in last 24 hours"),
    ("acct_info_txn_activity_year","int",     "acctInfo.txnActivityYear","Txns on cardholder account in last year"),
    ("acct_info_prov_attempts_day","int",     "acctInfo.provAttemptDay","Provisioning attempts in last 24 hours"),
    ("acct_info_nb_purchase_account","int",   "acctInfo.nbPurchaseAccount","Purchases with account in last 6 months"),
    ("ship_addr_match",           "enum",     "shipAddrMatch",         "Y=Shipping addr matches billing addr, N=No"),
    ("ship_addr_usage_ind",       "enum",     "shipAddrUsageInd",      "01=This txn, 02=<30d, 03=30-60d, 04=>60d"),
    ("bill_addr_city",            "str",      "billAddrCity",          "Billing address city"),
    ("bill_addr_country",         "str",      "billAddrCountry",       "ISO 3166-1 numeric billing country code"),
    ("bill_addr_state",           "str",      "billAddrState",         "Billing state/province (ISO 3166-2 subdivision)"),
    ("email",                     "str",      "email",                 "Cardholder email (hashed SHA-256 in output)"),

    # ── Device / Browser Fingerprint ──────────────────────────────────────────
    ("browser_accept_header",     "str",      "browserAcceptHeader",   "HTTP Accept header from cardholder browser"),
    ("browser_ip",                "str",      "browserIP",             "Cardholder IP address (IPv4 or IPv6)"),
    ("browser_java_enabled",      "bool",     "browserJavaEnabled",    "Whether browser executes Java"),
    ("browser_javascript_enabled","bool",     "browserJavascriptEnabled","Whether browser executes JavaScript"),
    ("browser_language",          "str",      "browserLanguage",       "Browser language (IETF BCP 47 e.g. en-US)"),
    ("browser_color_depth",       "enum",     "browserColorDepth",     "1/4/8/15/16/24/32/48 bits"),
    ("browser_screen_height",     "int",      "browserScreenHeight",   "Screen height in pixels"),
    ("browser_screen_width",      "int",      "browserScreenWidth",    "Screen width in pixels"),
    ("browser_tz",                "int",      "browserTZ",             "UTC offset in minutes (e.g. -300 = UTC-5)"),
    ("browser_user_agent",        "str",      "browserUserAgent",      "Full browser User-Agent string"),
    ("sdk_app_id",                "str",      "sdkAppID",              "Unique UUID per 3DS SDK installation"),
    ("sdk_enc_data",              "str",      "sdkEncData",            "JWE-encrypted device data blob from SDK"),
    ("sdk_ephem_pub_key",         "str",      "sdkEphemPubKey",        "Ephemeral public key from SDK (JWK format)"),
    ("sdk_max_timeout",           "int",      "sdkMaxTimeout",         "Max time (minutes) for challenge completion"),
    ("sdk_reference_number",      "str",      "sdkReferenceNumber",    "EMVCo-assigned SDK reference number"),

    # ── Merchant & Acquirer Information ───────────────────────────────────────
    ("merchant_id",               "str",      "merchantID",            "Acquirer-assigned merchant identifier"),
    ("merchant_name",             "str",      "merchantName",          "DBA name of merchant"),
    ("mcc",                       "str",      "mcc",                   "ISO 18245 Merchant Category Code (4-digit)"),
    ("acquirer_bin",              "str",      "acquirerBIN",           "Acquirer's BIN (6–11 digits)"),
    ("acquirer_merchant_id",      "str",      "acquirerMerchantID",    "Acquirer-assigned merchant ID (up to 15 chars)"),
    ("merchant_country_code",     "str",      "merchantCountryCode",   "ISO 3166-1 numeric merchant country code"),

    # ── Purchase / Transaction Details ────────────────────────────────────────
    ("purchase_amount",           "float",    "purchaseAmount",        "Purchase amount in minor currency units"),
    ("purchase_currency",         "str",      "purchaseCurrency",      "ISO 4217 numeric currency code (e.g. 840=USD)"),
    ("purchase_exponent",         "int",      "purchaseExponent",      "Minor unit exponent (e.g. 2 for USD)"),
    ("purchase_date",             "datetime", "purchaseDate",          "UTC datetime of purchase: YYYYMMDDHHmmss"),
    ("trans_type",                "enum",     "transType",             "01=Goods/Service, 03=Check Acceptance, 10=Account Funding, 11=Quasi-Cash, 28=Prepaid Activation"),
    ("recurring_expiry",          "str",      "recurringExpiry",       "YYYYMMDD — last date of recurring auth"),
    ("recurring_frequency",       "int",      "recurringFrequency",    "Days between recurring charges"),

    # ── Authentication Request / Response ─────────────────────────────────────
    ("three_ds_requestor_auth_ind","enum",    "threeDSRequestorAuthInd","01=Payment, 02=Recurring initial, 03=Instalment initial, 04=Add card, 05=Maintain card, 06=Cardholder verification, 07=Billing agreement"),
    ("three_ds_comp_ind",         "enum",     "threeDSCompInd",        "Y=Versioning completed, N=Versioning not completed, U=Unknown"),
    ("acs_challenge_mandated",    "enum",     "acsChallengeMandate",   "Y=Challenge required by ACS policy, N=Not required"),
    ("authentication_type",       "enum",     "authenticationType",    "01=Static, 02=Dynamic, 03=OOB, 04=Decoupled"),
    ("trans_status",              "enum",     "transStatus",           "Y=Auth successful, N=Not auth, U=Auth could not be performed, A=Attempts processing, C=Challenge required, R=Auth rejected, I=Info only"),
    ("trans_status_reason",       "enum",     "transStatusReason",     "01=Card auth failed, 02=Unknown device, 03=Unsupported device, 04=Exceeds auth freq limit, 05=Expired card, 06=Invalid card number, 07=Invalid transaction, 08=No card record, 09=Security failure, 10=Stolen card, 11=Suspected fraud, 12=Transaction not permitted to cardholder, 13=Cardholder not enrolled in service, 14=Unexpected callback, 15-79=Reserved, 80-99=DS/ACS specific"),
    ("eci",                       "str",      "eci",                   "Electronic Commerce Indicator: 02/05=Full auth, 01/06=Attempts, 07=Not auth (Visa/MC mapping)"),
    ("authentication_value",      "str",      "authenticationValue",   "28-byte base64 CAVV/AAV value from ACS"),
    ("acs_reference_number",      "str",      "acsReferenceNumber",    "Unique reference number assigned by ACS"),
    ("ds_reference_number",       "str",      "dsReferenceNumber",     "Unique reference number assigned by DS"),
    ("challenge_completed",       "bool",     "challengeCompleted",    "Whether cardholder completed challenge flow"),
    ("challenge_cancel_ind",      "enum",     "challengeCancelInd",    "01=Cardholder selected Cancel, 02=Reserved, 03=Txn timed out, 04=Timed out—decoupled, 05=Error, 06=Txn error, 07=Unknown"),

    # ── Prior Authentication / 3RI ─────────────────────────────────────────────
    ("three_ds_requestor_prior_auth_ind","enum","threeDSRequestorPriorAuthInd","01=Frictionless in current session, 02=Cardholder challenged, 03=AVS verified, 04=Other issuer methods"),
    ("prior_auth_method",         "enum",     "priorAuthMethod",       "01=Frictionless, 02=ACS challenged, 03=AVS verified, 04=Other"),
    ("prior_auth_timestamp",      "str",      "priorAuthTimestamp",    "YYYYMMDDHHmm UTC of prior auth"),

    # ── Risk / ACS Signals ────────────────────────────────────────────────────
    ("ship_indicator",            "enum",     "shipIndicator",         "01=Billing=Shipping, 02=Verified addr, 03=Different from billing, 04=Ship-to-store, 05=Digital goods, 06=Travel/event tickets, 07=Other"),
    ("delivery_timeframe",        "enum",     "deliveryTimeframe",     "01=Electronic delivery, 02=Same day, 03=Overnight, 04=2+ days"),
    ("reorder_items_ind",         "enum",     "reorderItemsInd",       "01=First time ordered, 02=Reordered"),
    ("pre_order_purchase_ind",    "enum",     "preOrderPurchaseInd",   "01=Merchandise available, 02=Future availability"),
    ("gift_card_amount",          "float",    "giftCardAmount",        "Total purchase amount of prepaid/gift cards"),
    ("gift_card_count",           "int",      "giftCardCount",         "Total count of prepaid/gift cards purchased"),
    ("purchase_instal_data",      "int",      "purchaseInstalData",    "Max authorisations for instalment payment"),

    # ── Derived / Synthetic Risk Signals (not EMVCo but standard ML features) ─
    ("velocity_1h",               "int",      "DERIVED",               "Count of auth attempts from same IP in last 1 hour"),
    ("velocity_24h",              "int",      "DERIVED",               "Count of auth attempts from same IP in last 24 hours"),
    ("amount_vs_avg_ratio",       "float",    "DERIVED",               "purchaseAmount / rolling 30-day average for this acct"),
    ("new_device_flag",           "int",      "DERIVED",               "1 if device not seen in prior 90 days, else 0"),
    ("new_shipping_addr_flag",    "int",      "DERIVED",               "1 if shipping address first use, else 0"),
    ("cross_border_flag",         "int",      "DERIVED",               "1 if merchantCountryCode != billAddrCountry"),
    ("high_risk_mcc_flag",        "int",      "DERIVED",               "1 if MCC in high-risk category (6051,6211,7995,etc)"),
    ("time_since_acct_open_days", "int",      "DERIVED",               "Days since acctInfo.openAcctInd account was opened"),

    # ── Ground Truth (synthetic only) ─────────────────────────────────────────
    ("fraud_label",               "int",      "SYNTHETIC",             "1=Fraud, 0=Legitimate (ground truth for ML training)"),
    ("fraud_pattern",             "str",      "SYNTHETIC",             "Name of fraud pattern used to generate row, or 'normal'"),
]

# ── Convenience lookups ────────────────────────────────────────────────────────

# All column names in order
COLUMN_NAMES: list[str] = [c[0] for c in EMVCO_3DS_COLUMNS]

# dtype by column name
COLUMN_DTYPES: dict[str, str] = {c[0]: c[1] for c in EMVCO_3DS_COLUMNS}

# EMVCo element ID by column name (SYNTHETIC/DERIVED flagged)
COLUMN_ELEMENT_IDS: dict[str, str] = {c[0]: c[2] for c in EMVCO_3DS_COLUMNS}

# Human description by column name
COLUMN_DESCRIPTIONS: dict[str, str] = {c[0]: c[3] for c in EMVCO_3DS_COLUMNS}

# Columns that DatasetEngine always writes for both normal and fraud rows
CORE_COLUMNS = [
    "threeds_server_trans_id", "acs_trans_id", "ds_trans_id",
    "message_version", "device_channel",
    "three_ds_requestor_id", "three_ds_requestor_name",
    "acct_number", "card_expiry_date", "acct_id", "acct_type",
    "acct_info_chg_ind", "acct_info_open_acct_ind",
    "acct_info_txn_activity_day", "acct_info_txn_activity_year",
    "acct_info_nb_purchase_account",
    "browser_ip", "browser_language", "browser_user_agent",
    "browser_java_enabled", "browser_javascript_enabled",
    "browser_screen_height", "browser_screen_width",
    "browser_tz", "browser_color_depth",
    "merchant_id", "merchant_name", "mcc",
    "acquirer_bin", "acquirer_merchant_id", "merchant_country_code",
    "purchase_amount", "purchase_currency", "purchase_exponent", "purchase_date",
    "trans_type",
    "three_ds_requestor_auth_ind", "three_ds_comp_ind",
    "acs_challenge_mandated", "authentication_type",
    "trans_status", "eci",
    "challenge_completed",
    "ship_indicator", "delivery_timeframe",
    "velocity_1h", "velocity_24h",
    "amount_vs_avg_ratio", "new_device_flag", "new_shipping_addr_flag",
    "cross_border_flag", "high_risk_mcc_flag",
    "fraud_label", "fraud_pattern",
]

# ── Enum value pools (used by DatasetEngine generators) ───────────────────────

ENUM_POOLS: dict[str, list] = {
    "message_version":              ["2.1.0", "2.2.0", "2.3.1"],
    "device_channel":               ["01", "02", "02", "02", "03"],   # BRW-heavy
    "acct_type":                    ["01", "02", "03"],
    "acct_info_chg_ind":            ["01", "02", "03", "04"],
    "acct_info_open_acct_ind":      ["01", "02", "03", "04"],
    "acct_info_ship_addr_usage_ind":["01", "02", "03", "04"],
    "ship_addr_match":              ["Y", "N"],
    "ship_addr_usage_ind":          ["01", "02", "03", "04"],
    "trans_type":                   ["01", "01", "01", "10", "28"],
    "trans_status":                 ["Y", "Y", "Y", "A", "C", "N", "U"],
    "trans_status_reason":          ["01", "07", "09", "11", "13"],
    "three_ds_requestor_auth_ind":  ["01", "01", "01", "02", "04"],
    "three_ds_comp_ind":            ["Y", "Y", "N", "U"],
    "acs_challenge_mandated":       ["Y", "N", "N", "N"],
    "authentication_type":          ["01", "02", "02", "03", "04"],
    "challenge_cancel_ind":         ["01", "03", "04", "05"],
    "ship_indicator":               ["01", "02", "03", "04", "05", "06", "07"],
    "delivery_timeframe":           ["01", "02", "03", "04"],
    "reorder_items_ind":            ["01", "02"],
    "pre_order_purchase_ind":       ["01", "02"],
    "browser_color_depth":          ["24", "32", "16", "48"],
    "three_ds_requestor_prior_auth_ind": ["01", "02", "03", "04"],
    "prior_auth_method":            ["01", "02", "03", "04"],
}

# ISO 4217 numeric currency codes used in purchase_currency
CURRENCY_CODES: dict[str, str] = {
    "USD": "840", "EUR": "978", "GBP": "826", "JPY": "392",
    "AUD": "036", "CAD": "124", "CHF": "756", "SGD": "702",
    "INR": "356", "BRL": "986", "MXN": "484", "CNY": "156",
}

# High-risk MCCs (for high_risk_mcc_flag)
HIGH_RISK_MCCS: set[str] = {
    "6051",  # Non-FI, Foreign Currency, Money Orders
    "6211",  # Security Brokers / Dealers
    "7995",  # Betting, Casino Gambling
    "5912",  # Drug Stores, Pharmacies
    "7273",  # Dating / Escort Services
    "5966",  # Direct Marketing — Outbound Telemarketing
    "5993",  # Cigar Stores
    "4829",  # Wire Transfer Money Orders
    "6540",  # POI (Funding Transactions — Prepaid/Stored Value Load)
}

# MCC → human-readable merchant category (used in merchant generation)
MCC_CATEGORIES: dict[str, str] = {
    "5411": "Grocery Stores",
    "5812": "Eating Places, Restaurants",
    "5541": "Service Stations",
    "5999": "Miscellaneous Retail",
    "5732": "Electronics Stores",
    "5311": "Department Stores",
    "7011": "Hotels & Lodging",
    "4511": "Airlines",
    "5912": "Drug Stores",
    "7995": "Gambling",
    "6011": "ATM Cash Advances",
    "4814": "Telecom Services",
    "5045": "Computers & Peripherals",
    "7372": "Software & SaaS",
    "6051": "Crypto / Money Services",
    "4829": "Wire Transfers",
    "5094": "Jewelry & Watches",
    "5065": "Electrical Parts",
    "5651": "Family Clothing",
    "5661": "Shoe Stores",
}

# Scenario → typical MCC codes (used by blueprint prompt and DatasetEngine)
SCENARIO_MCC_MAP: dict[str, list[str]] = {
    "bin attack":          ["5999", "5045", "7372"],
    "card testing":        ["5999", "5045", "5411"],
    "account takeover":    ["5732", "5311", "5094", "7011", "4511"],
    "money laundering":    ["6051", "4829", "6011"],
    "refund fraud":        ["5999", "5311", "5651"],
    "identity fraud":      ["5732", "5311", "5094"],
    "phishing":            ["4829", "6051", "5999"],
    "synthetic identity":  ["5311", "5732", "5651", "5661"],
    "friendly fraud":      ["5812", "5999", "5651"],
    "triangulation fraud": ["5999", "5045", "5732"],
}

# ── Compact column reference for prompt injection ─────────────────────────────

def build_column_reference_table() -> str:
    """
    Returns a Markdown table of EMVCo 3DS columns for injection into prompts.
    Covers the CORE_COLUMNS subset for conciseness.
    """
    lines = [
        "| Column Name | EMVCo Element | Type | Description |",
        "|---|---|---|---|",
    ]
    for col, dtype, elem_id, desc in EMVCO_3DS_COLUMNS:
        if col in CORE_COLUMNS:
            short_desc = desc[:80] + "…" if len(desc) > 80 else desc
            lines.append(f"| `{col}` | `{elem_id}` | {dtype} | {short_desc} |")
    return "\n".join(lines)